version: '3'
services:
  app:
    image: node:14
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: bash -c "npm install && npm run start"
    environment:
      NODE_ENV: development
#   db:
#     image: postgres:13
#     ports: 
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#       - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
#       - ./initdb/db.sql:/docker-entrypoint-initdb.d/db.sql
#     environment:
#       POSTGRES_DB: cscd
#       POSTGRES_USER: please_user
#       POSTGRES_PASSWORD: please
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U please_user"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   pgdata:
