import type { Sequelize } from "sequelize";
import { entity as _entity } from "./entity";
import type { entityAttributes, entityCreationAttributes } from "./entity";
import { entity_attr as _entity_attr } from "./entity_attr";
import type { entity_attrAttributes, entity_attrCreationAttributes } from "./entity_attr";
import { entity_attr_log as _entity_attr_log } from "./entity_attr_log";
import type { entity_attr_logAttributes, entity_attr_logCreationAttributes } from "./entity_attr_log";
import { entity_entity as _entity_entity } from "./entity_entity";
import type { entity_entityAttributes, entity_entityCreationAttributes } from "./entity_entity";
import { entity_stage as _entity_stage } from "./entity_stage";
import type { entity_stageAttributes, entity_stageCreationAttributes } from "./entity_stage";
import { ref_action as _ref_action } from "./ref_action";
import type { ref_actionAttributes, ref_actionCreationAttributes } from "./ref_action";
import { ref_actor as _ref_actor } from "./ref_actor";
import type { ref_actorAttributes, ref_actorCreationAttributes } from "./ref_actor";
import { ref_attr as _ref_attr } from "./ref_attr";
import type { ref_attrAttributes, ref_attrCreationAttributes } from "./ref_attr";
import { ref_attr_actor as _ref_attr_actor } from "./ref_attr_actor";
import type { ref_attr_actorAttributes, ref_attr_actorCreationAttributes } from "./ref_attr_actor";
import { ref_attr_dict as _ref_attr_dict } from "./ref_attr_dict";
import type { ref_attr_dictAttributes, ref_attr_dictCreationAttributes } from "./ref_attr_dict";
import { ref_attr_group as _ref_attr_group } from "./ref_attr_group";
import type { ref_attr_groupAttributes, ref_attr_groupCreationAttributes } from "./ref_attr_group";
import { ref_attr_group_actor as _ref_attr_group_actor } from "./ref_attr_group_actor";
import type { ref_attr_group_actorAttributes, ref_attr_group_actorCreationAttributes } from "./ref_attr_group_actor";
import { ref_attr_outer as _ref_attr_outer } from "./ref_attr_outer";
import type { ref_attr_outerAttributes, ref_attr_outerCreationAttributes } from "./ref_attr_outer";
import { ref_entity_filter as _ref_entity_filter } from "./ref_entity_filter";
import type { ref_entity_filterAttributes, ref_entity_filterCreationAttributes } from "./ref_entity_filter";
import { ref_entity_filter_attr as _ref_entity_filter_attr } from "./ref_entity_filter_attr";
import type { ref_entity_filter_attrAttributes, ref_entity_filter_attrCreationAttributes } from "./ref_entity_filter_attr";
import { ref_entity_type as _ref_entity_type } from "./ref_entity_type";
import type { ref_entity_typeAttributes, ref_entity_typeCreationAttributes } from "./ref_entity_type";
import { ref_route as _ref_route } from "./ref_route";
import type { ref_routeAttributes, ref_routeCreationAttributes } from "./ref_route";
import { ref_stage as _ref_stage } from "./ref_stage";
import type { ref_stageAttributes, ref_stageCreationAttributes } from "./ref_stage";
import { ref_stage_action as _ref_stage_action } from "./ref_stage_action";
import type { ref_stage_actionAttributes, ref_stage_actionCreationAttributes } from "./ref_stage_action";
import { ref_stage_action_actor as _ref_stage_action_actor } from "./ref_stage_action_actor";
import type { ref_stage_action_actorAttributes, ref_stage_action_actorCreationAttributes } from "./ref_stage_action_actor";
import { ref_stage_action_stage as _ref_stage_action_stage } from "./ref_stage_action_stage";
import type { ref_stage_action_stageAttributes, ref_stage_action_stageCreationAttributes } from "./ref_stage_action_stage";
export { _entity as entity, _entity_attr as entity_attr, _entity_attr_log as entity_attr_log, _entity_entity as entity_entity, _entity_stage as entity_stage, _ref_action as ref_action, _ref_actor as ref_actor, _ref_attr as ref_attr, _ref_attr_actor as ref_attr_actor, _ref_attr_dict as ref_attr_dict, _ref_attr_group as ref_attr_group, _ref_attr_group_actor as ref_attr_group_actor, _ref_attr_outer as ref_attr_outer, _ref_entity_filter as ref_entity_filter, _ref_entity_filter_attr as ref_entity_filter_attr, _ref_entity_type as ref_entity_type, _ref_route as ref_route, _ref_stage as ref_stage, _ref_stage_action as ref_stage_action, _ref_stage_action_actor as ref_stage_action_actor, _ref_stage_action_stage as ref_stage_action_stage, };
export type { entityAttributes, entityCreationAttributes, entity_attrAttributes, entity_attrCreationAttributes, entity_attr_logAttributes, entity_attr_logCreationAttributes, entity_entityAttributes, entity_entityCreationAttributes, entity_stageAttributes, entity_stageCreationAttributes, ref_actionAttributes, ref_actionCreationAttributes, ref_actorAttributes, ref_actorCreationAttributes, ref_attrAttributes, ref_attrCreationAttributes, ref_attr_actorAttributes, ref_attr_actorCreationAttributes, ref_attr_dictAttributes, ref_attr_dictCreationAttributes, ref_attr_groupAttributes, ref_attr_groupCreationAttributes, ref_attr_group_actorAttributes, ref_attr_group_actorCreationAttributes, ref_attr_outerAttributes, ref_attr_outerCreationAttributes, ref_entity_filterAttributes, ref_entity_filterCreationAttributes, ref_entity_filter_attrAttributes, ref_entity_filter_attrCreationAttributes, ref_entity_typeAttributes, ref_entity_typeCreationAttributes, ref_routeAttributes, ref_routeCreationAttributes, ref_stageAttributes, ref_stageCreationAttributes, ref_stage_actionAttributes, ref_stage_actionCreationAttributes, ref_stage_action_actorAttributes, ref_stage_action_actorCreationAttributes, ref_stage_action_stageAttributes, ref_stage_action_stageCreationAttributes, };
export declare function initModels(sequelize: Sequelize): {
    entity: typeof _entity;
    entity_attr: typeof _entity_attr;
    entity_attr_log: typeof _entity_attr_log;
    entity_entity: typeof _entity_entity;
    entity_stage: typeof _entity_stage;
    ref_action: typeof _ref_action;
    ref_actor: typeof _ref_actor;
    ref_attr: typeof _ref_attr;
    ref_attr_actor: typeof _ref_attr_actor;
    ref_attr_dict: typeof _ref_attr_dict;
    ref_attr_group: typeof _ref_attr_group;
    ref_attr_group_actor: typeof _ref_attr_group_actor;
    ref_attr_outer: typeof _ref_attr_outer;
    ref_entity_filter: typeof _ref_entity_filter;
    ref_entity_filter_attr: typeof _ref_entity_filter_attr;
    ref_entity_type: typeof _ref_entity_type;
    ref_route: typeof _ref_route;
    ref_stage: typeof _ref_stage;
    ref_stage_action: typeof _ref_stage_action;
    ref_stage_action_actor: typeof _ref_stage_action_actor;
    ref_stage_action_stage: typeof _ref_stage_action_stage;
};
